yolo_model:

  config_file:
    name: v2_test.cfg
  weight_file:
    name: v2_test.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - traffic light
      - dynamic
      - static
      - left
      - right
      - parking
